### ISSUE TITLE
Lynis error: permissions are not strict enough

### ISSUE THREAD

**Issue by nununo** [infothrill/ansible-role-lynis#55]
After installing Lynis in a Debian 10 using v4.0.0 I'm getting this error:

```text
Fatal error: permissions of file /opt/lynis/db/languages/en are not strict enough. Access to 'owner' should be read-write, or read. Change with: chmod u=rw /opt/lynis/db/languages/en
```

Once I follow the suggestion I get:
```text
Fatal error: permissions of file /opt/lynis/db/languages/en are not strict enough. Access to 'group' should be read-write, read, or none. Change with: chmod g=r /opt/lynis/db/languages/en
```

And once I follow this suggestion i get:
```text
Fatal error: permissions of file /opt/lynis/include/parameters are not strict enough. Access to 'owner' should be read-write, or read. Change with: chmod u=rw /opt/lynis/include/parameters
```

Lynis documentation says this:
> To protect alteration of the files, Lynis perform a few security checks. If the related files are not owned by root, or their 
permissions are not strict enough, Lynis will show this on screen, including the commands to fix it. Usually it is caused because files were **untarred by a user other than root**.

Looking at `install.yml` it seems like in commit 4e08756223eb5d3a11554d6c13495d1c5dfe2467 the untar file permissions where forced to 750 to comply with ansible-lint. But it seems like Lynis is not pleased unless it sees is files with 640.

And yet, changing the untar permissions from 750 to 640 will probably not suffice because I'm guessing that the actual executable probably still needs to be 750.

I hope this helps. Thanks in advance.

**Comment by infothrill** [comment]
version 4.1.0 released, which fixes this

**Comment by nununo** [comment]
Wow! Thank you for such a quick reaction!
